spring:
  application:
    name: registry
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=registry_db;createDatabaseIfNotExist=true;encrypt=true;trustServerCertificate=true;
    username: sa
    password: YourPassword123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
#    properties:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.SQLServerDialect
#      format_sql: true